### ISSUE TITLE
The descriptions are incomplete in that the generative relationships specified are not stochastic until the probability distribution is also given

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/bbousims#16]
<img width="1282" alt="Screenshot 2024-04-30 at 05 29 27" src="https://github.com/poissonconsulting/bbousims/assets/613671/050c5e6e-754e-41a9-8c75-27286279c8c6">

**Comment by joethorley** [comment]
ie the relationship above is simply deterministic with a logit transform

**Comment by sebdalgarno** [comment]
right - would be acceptable to just change \sim to =?

**Comment by joethorley** [comment]
Yes but should also specify that deterministic unless the distribution is specifed as well.

**Comment by sebdalgarno** [comment]
right in this case the only stochastic part is the generation of the random effects from a normal distribution and use-specified SD
